server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fsm
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: MQa12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:resources/mapper/*.xml
  type-aliases-package: top.atluofu.fsm.dao
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl